import { ThemeProvider } from '@/components/elements/theme-provider'
import { Inter } from 'next/font/google'
import './globals.css'
const inter = Inter({
	weight: ['400', '500', '700'],
	subsets: ['latin'],
	display: 'swap',
})

export const metadata = {
	title: 'Aixus - AI-Powered Content Generator Admin Dashboard Next.js Template',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}